# Generated by Django 4.2.5 on 2023-10-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dict',
            old_name='trnslt',
            new_name='translation',
        ),
    ]
